'''title'''
__title__ = 'paperdl'
'''description'''
__description__ = 'Paperdl: Search and download paper from specific websites'
'''url'''
__url__ = 'https://github.com/CharlesPikachu/paperdl'
'''version'''
__version__ = '0.1.4'
'''author'''
__author__ = 'Charles'
'''email'''
__email__ = 'charlesblwx@gmail.com'
'''license'''
__license__ = 'Apache License 2.0'
'''copyright'''
__copyright__ = 'Copyright 2022 Charles'